<h2>Almere</h2>
<p>De gemeente Almere heeft 195.710 inwoners (1 november 2013, bron: CBS) en grenst aan de gemeenten Lelystad en Zeewolde. Bovendien ligt Almere aan het Gooimeer, IJmeer en Markermeer. De stad ligt geheel onder zeeniveau (2 tot 5 meter).</p>
<p>Almere is in de tweede helft van de twintigste eeuw ontwikkeld als tweede grote stad in de provincie Flevoland. Inmiddels is het Lelystad, de hoofdstad van Flevoland, in inwonertal ruimschoots voorbijgestreefd en behoort Almere tot de 10 grootste gemeenten van Nederland. Ook is het een van de snelst groeiende steden in Nederland.</p>

<h2>Geschiedenis</h2>
<p>Van oorsprong waren de IJsselmeerpolders vooral, of zelfs uitsluitend, bedoeld als landbouwgrond. Na de Tweede Wereldoorlog kwam men echter tot het inzicht dat de snel groeiende bevolking van met name Amsterdam voor een deel elders gehuisvest zou moeten worden. Zo ontwierp men twee steden in de polders Oostelijk en Zuidelijk Flevoland. De stad in Oostelijk Flevoland werd Lelystad. De stad in zuidelijk Flevoland werd op de eerste schetsen nog Zuidweststad genoemd, maar kreeg in de jaren zeventig de naam Almere, naar de vroeg-middeleeuwse naam van de Zuiderzee.</p>
<p>De eerste aanzet voor de bouw van Almere werd gegeven op 30 september 1975 en de eerste woningen in Almere werden opgeleverd in november 1976. De stad werd toen nog direct bestuurd door het Openbaar Lichaam Zuidelijke IJsselmeerpolders (Z.IJ.P.), met een landdrost aan het hoofd. Het landelijk voorgeschreven bouwprogramma voor de nieuwe stad bestond voor 70 tot 80 procent uit sociale woningbouw. Als opdrachtgever en voorbereider van de woningbouw in Almere werd in 1975 de Stichting Woningbouw Almere opgericht, een onderdeel van de Rijksdienst voor de IJsselmeerpolders.</p>
<p>Eind 1979 werd op initiatief van landdrost Han Lammers de algemene Woningbouwvereniging Almere opgericht. Het idee was dat deze vereniging de sociale huurwoningen van de SWA in eigendom en beheer zou overnemen en de resterende bouwopgave van sociale huurwoningen in Almere voortaan voor haar rekening zou nemen. Geheel tegen de tijdgeest in volgde bijna gelijktijdig de oprichting van de christelijke woningbouwvereniging Goedestede, door gelovige Almeerders die hoopten te bevorderen dat er in Almere meer aanwas zou komen voor de nieuwe lokale protestantse kerkgemeenschap.</p>
<p>Per 1984 werd wat er nog over was van het OL ZIJP bij wet opgedeeld in de gemeenten Almere en Zeewolde. De gemeente Almere beschouwt zich als de rechtsopvolger van het Openbaar Lichaam en voert ook hetzelfde wapen. Tot 1986, de oprichting van de provincie Flevoland, nam het Ministerie van Binnenlandse Zaken de provincietaken waar.</p>
<p>Oorspronkelijk was Almere opgezet als meerkernige stad. Dit beleid is gedeeltelijk losgelaten. Almere Buiten en Almere Stad zijn via de wijk Tussen de Vaarten aan elkaar gegroeid. Tussen de oudste en de nieuwste woonwijken ziet men duidelijk een veranderd woningbouwbeleid terug: in de jaren zeventig was dit gericht op gelijkvormigheid en functionaliteit, in de jaren negentig werd het de trend meer exclusieve en opvallende woningen te bouwen, bijvoorbeeld in de Regenboogbuurt.</p>
<p>Het centrum van Almere Stad, het grootste stadsdeel, is sterk aan het uitbreiden. In 2006 is het eerste deel van het nieuw gebouwde stadscentrum Citymall Almere opgeleverd. Het voornaamste gebouw hiervan is de Citadel, ontworpen door Pritzker Prize-winnaar Christian de Portzamparc. Begin 2007 zijn de nieuwe Schouwburg Almere en Kunstencentrum de Kunstlinie in gebruik genomen. Het opvallende pand, gelegen aan het Weerwater, is op 8 juni 2007 officieel geopend door koningin Beatrix.</p>
